import { describe, expect, it } from "vitest";
import tokens from "../../../design-tokens/tokens.json";
import { FONT_VARIABLES, buildTokensCss, fontStack } from "./build";
import type { TokensFile } from "./types";

const file: TokensFile = tokens;
const css = buildTokensCss(file);

/** Body of the first rule whose selector is exactly `selector`. */
function block(selector: string): string {
  const start = css.indexOf(`${selector} {`);
  expect(start, `missing block "${selector}"`).toBeGreaterThanOrEqual(0);
  return css.slice(start, css.indexOf("}", start));
}

const resolve = (value: string) => value.replace(/^\{([a-z0-9-]+)\}$/, "var(--$1)");

describe("buildTokensCss", () => {
  it("starts with a do-not-edit header", () => {
    expect(css.startsWith("/* Generated by scripts/build-tokens.ts")).toBe(true);
  });

  it("declares every colour with its Paper value on :root", () => {
    const root = block(":root");
    for (const t of file.color.tokens) {
      expect(root).toContain(`--${t.name}: ${resolve(t.value.light)};`);
    }
  });

  it("declares every colour with its Darkroom value for data-theme=dark and for a dark OS preference", () => {
    const explicit = block('[data-theme="dark"]');
    const media = block(':root:not([data-theme="light"])');
    for (const t of file.color.tokens) {
      expect(explicit).toContain(`--${t.name}: ${resolve(t.value.dark)};`);
      expect(media).toContain(`--${t.name}: ${resolve(t.value.dark)};`);
    }
    expect(css).toContain("@media (prefers-color-scheme: dark) {");
  });

  it("re-declares Paper values for data-theme=light so a light scope works inside a dark page", () => {
    const light = block('[data-theme="light"]');
    for (const t of file.color.tokens) {
      expect(light).toContain(`--${t.name}: ${resolve(t.value.light)};`);
    }
  });

  it("resolves the focus alias in every theme block", () => {
    expect(css).not.toContain("{cobalt}");
    for (const sel of [":root", '[data-theme="dark"]', '[data-theme="light"]', ':root:not([data-theme="light"])']) {
      expect(block(sel)).toContain("--focus: var(--cobalt);");
    }
  });

  it("themes the shadows", () => {
    for (const t of file.shadow.tokens) {
      expect(block(":root")).toContain(`--${t.name}: ${t.value.light};`);
      expect(block('[data-theme="dark"]')).toContain(`--${t.name}: ${t.value.dark};`);
    }
  });

  it("sets color-scheme per theme", () => {
    expect(block(":root")).toContain("color-scheme: light;");
    expect(block('[data-theme="dark"]')).toContain("color-scheme: dark;");
  });

  it("puts spacing, tilt and grain opacity on :root", () => {
    const root = block(":root");
    expect(root).toContain("--space-4: 16px;");
    expect(root).toContain("--space-16: 64px;");
    expect(root).toContain("--tilt-wild: -4deg;");
    expect(root).toContain("--grain-opacity: 0.07;");
  });

  it("resets Tailwind's default scales in @theme static", () => {
    const theme = block("@theme static");
    for (const ns of ["color", "font", "text", "radius", "shadow"]) {
      expect(theme).toContain(`--${ns}-*: initial;`);
    }
  });

  it("maps font families onto the next/font variables", () => {
    const theme = block("@theme static");
    expect(theme).toContain('--font-display: var(--font-fraunces), Georgia, "Times New Roman", serif;');
    expect(theme).toContain('--font-hand: var(--font-patrick-hand), "Segoe Print", cursive;');
  });

  it("emits every text style with its line height, weight and tracking", () => {
    const theme = block("@theme static");
    expect(theme).toContain("--text-display-hero: 88px;");
    expect(theme).toContain("--text-display-hero--line-height: 84px;");
    expect(theme).toContain("--text-display-hero--font-weight: 500;");
    expect(theme).toContain("--text-display-hero--letter-spacing: -0.025em;");
    expect(theme).toContain("--text-label--letter-spacing: 0.08em;");
    expect(theme).not.toContain("--text-title--letter-spacing");
    const styleCount = file.type.groups.flatMap((g) => g.styles).length;
    // Single-hyphen-separated names only: excludes the --line-height companions,
    // which are also declared in px and would otherwise double-count.
    expect(theme.match(/--text-[a-z]+(?:-[a-z]+)*: \d+px;/g)).toHaveLength(styleCount);
  });

  it("emits the radius tokens under Tailwind's radius namespace", () => {
    const theme = block("@theme static");
    expect(theme).toContain("--radius-sm: 2px;");
    expect(theme).toContain("--radius-pill: 999px;");
  });

  it("maps every colour to a Tailwind colour utility in @theme inline", () => {
    const inline = block("@theme inline");
    for (const t of file.color.tokens) {
      expect(inline).toContain(`--color-${t.name}: var(--${t.name});`);
    }
  });
});

describe("fontStack", () => {
  it("swaps the first quoted family for the next/font variable", () => {
    expect(fontStack(file, "sans")).toBe(
      'var(--font-be-vietnam-pro), system-ui, -apple-system, "Segoe UI", sans-serif',
    );
  });

  it("has a next/font variable for every family in tokens.json", () => {
    expect(Object.keys(FONT_VARIABLES).sort()).toEqual(Object.keys(file.type.families).sort());
  });
});
