import type { Theme, TokensFile } from "./types";

/** CSS variables that next/font sets on <html> for each family (see src/app/fonts.ts). */
export const FONT_VARIABLES = {
  display: "--font-fraunces",
  sans: "--font-be-vietnam-pro",
  mono: "--font-space-mono",
  hand: "--font-patrick-hand",
} as const;

export type FontFamilyToken = keyof typeof FONT_VARIABLES;

const HEADER =
  "/* Generated by scripts/build-tokens.ts from design-tokens/tokens.json. Do not edit: run `pnpm tokens`. */";

const decl = (name: string, value: string) => `  --${name}: ${value};`;

/** `{cobalt}` → `var(--cobalt)`; anything else is returned as is. */
const resolveAlias = (value: string) => value.replace(/^\{([a-z0-9-]+)\}$/, "var(--$1)");

function rule(selector: string, lines: string[], indent = ""): string {
  return [`${indent}${selector} {`, ...lines.map((l) => indent + l), `${indent}}`].join("\n");
}

function themed(tokens: TokensFile, theme: Theme): string[] {
  return [
    ...tokens.color.tokens.map((t) => decl(t.name, resolveAlias(t.value[theme]))),
    ...tokens.shadow.tokens.map((t) => decl(t.name, t.value[theme])),
    `  color-scheme: ${theme};`,
  ];
}

/** The family's stack with its first (quoted) family replaced by the next/font variable. */
export function fontStack(tokens: TokensFile, family: FontFamilyToken): string {
  return tokens.type.families[family].replace(/^"[^"]+"/, `var(${FONT_VARIABLES[family]})`);
}

/**
 * Under 600px each desktop style steps down to its phone style (design system README, Type).
 * Re-pointing the desktop variables means every CSS Module and utility follows without a
 * media query of its own. `display-hero` is the exception: it drops to display-l's desktop
 * values, which are written out because display-l itself is re-pointed on phones.
 */
const PHONE_STYLES: Array<[desktop: string, mobile: string]> = [
  ["body", "body-mobile"],
  ["body-sm", "body-sm-mobile"],
  ["title", "title-mobile"],
  ["display-xl", "display-mobile"],
  ["display-l", "display-mobile"],
];

function phoneTextStyles(tokens: TokensFile): string[] {
  const styles = new Map(tokens.type.groups.flatMap((g) => g.styles).map((s) => [s.name, s]));
  const pointed = PHONE_STYLES.flatMap(([desktop, mobile]) => {
    const target = styles.get(mobile);
    if (!target) throw new Error(`tokens.json has no "${mobile}" style for phones`);
    return [
      decl(`text-${desktop}`, `var(--text-${mobile})`),
      decl(`text-${desktop}--line-height`, `var(--text-${mobile}--line-height)`),
      decl(`text-${desktop}--font-weight`, `var(--text-${mobile}--font-weight)`),
      decl(
        `text-${desktop}--letter-spacing`,
        target.letterSpacing ? `var(--text-${mobile}--letter-spacing)` : "normal",
      ),
    ];
  });
  const heroTarget = styles.get("display-l");
  if (!heroTarget) throw new Error('tokens.json has no "display-l" style for the phone hero');
  return [
    ...pointed,
    decl("text-display-hero", heroTarget.fontSize),
    decl("text-display-hero--line-height", heroTarget.lineHeight),
    decl("text-display-hero--font-weight", String(heroTarget.fontWeight)),
    decl("text-display-hero--letter-spacing", heroTarget.letterSpacing ?? "normal"),
  ];
}

export function buildTokensCss(tokens: TokensFile): string {
  const staticVars = [
    ...tokens.spacing.tokens.map((t) => decl(t.name, t.value)),
    ...tokens.tilt.tokens.map((t) => decl(t.name, t.value)),
    ...tokens.opacity.tokens.map((t) => decl(t.name, t.value)),
  ];

  const families = Object.keys(FONT_VARIABLES) as FontFamilyToken[];
  const textStyles = tokens.type.groups
    .flatMap((g) => g.styles)
    .flatMap((s) => [
      decl(`text-${s.name}`, s.fontSize),
      decl(`text-${s.name}--line-height`, s.lineHeight),
      decl(`text-${s.name}--font-weight`, String(s.fontWeight)),
      ...(s.letterSpacing ? [decl(`text-${s.name}--letter-spacing`, s.letterSpacing)] : []),
    ]);

  // `static` makes Tailwind emit every variable, so CSS Modules can read them too.
  const themeStatic = [
    decl("color-*", "initial"),
    decl("font-*", "initial"),
    decl("text-*", "initial"),
    decl("radius-*", "initial"),
    decl("shadow-*", "initial"),
    ...families.map((f) => decl(`font-${f}`, fontStack(tokens, f))),
    ...textStyles,
    ...tokens.radius.tokens.map((t) => decl(t.name, t.value)),
  ];

  // `inline` makes bg-cobalt compile to var(--cobalt), so utilities follow the active theme.
  const themeInline = tokens.color.tokens.map((t) => decl(`color-${t.name}`, `var(--${t.name})`));

  return [
    HEADER,
    "",
    rule(":root", [...themed(tokens, "light"), ...staticVars]),
    "",
    "@media (prefers-color-scheme: dark) {",
    rule(':root:not([data-theme="light"])', themed(tokens, "dark"), "  "),
    "}",
    "",
    rule('[data-theme="light"]', themed(tokens, "light")),
    "",
    rule('[data-theme="dark"]', themed(tokens, "dark")),
    "",
    rule("@theme static", themeStatic),
    "",
    rule("@theme inline", themeInline),
    "",
    "@media (max-width: 599px) {",
    rule(":root", phoneTextStyles(tokens), "  "),
    "}",
    "",
  ].join("\n");
}
